# Generated by Django 4.0.5 on 2022-07-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_agent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
