# Generated by Django 4.0.5 on 2022-07-22 06:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_image_listing_image_1_listing_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
